name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install uv
        run: pip install uv

      - name: Set up virtual environment
        run: uv venv .venv

      - name: Activate virtual environment and install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev,test]
          uv pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          uv run pytest tests/ --cov=fluent_mcp --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Set up virtual environment
        run: uv venv .venv

      - name: Activate venv and install linting tools
        run: |
          source .venv/bin/activate
          uv pip install flake8 black isort

      - name: Run linters
        run: |
          source .venv/bin/activate
          uv run flake8 fluent_mcp/ tests/
          uv run black --check fluent_mcp/ tests/
          uv run isort --check fluent_mcp/ tests/
